### ISSUE TITLE
Arch Linux AUR not allowing for extrusion

### ISSUE THREAD

**Issue by andreyblend** [nkallen/plasticity#100]
Hello, I used yay to install plasticity-bin on my arch Linux system. The system is up to date with the latest Nvidia drivers. I am able to draw shapes using the various tools. However, when I click the yellow vertical line with sphere on top to drag to extrude, the extrusion does not work. I am also unable to use the sphere, cylinder, and corner box tools. I tried to install using dpkg from the .deb package which has seemed to solve the issue. However, some dependencies are not available on arch and as such features like exporting do not work. Can the AUR be updated to reflect the newer version of the beta. Thank you!

**Comment by nkallen** [comment]
Well I'm not maintaining those things... I am building deb because it's easy. I'm a Mac guy not a linux guy. Someone else was taking care of that aur stuff
