### ISSUE TITLE
about overlaping window of tools

### ISSUE THREAD

**Issue by lpslp** [nkallen/plasticity#102]
hi **nickkallen1**
when windows of program is not full screen, buttons rows is constantly overlapping with operation window which appear constantly. If you drop buttons of tools in wiewport and do not want do its personal shelfs not in viewport - then, probably, need to detect when operation window is cover buttons and tooltips of operations and move window somewhere else.
![image](https://user-images.githubusercontent.com/19380636/188278394-e8cb4639-7d1e-4dfa-b135-32ec1a7027c0.png)

or as in blender - fold in operation windows and unfold it by hotkey (blender F9)
![image](https://i.imgur.com/1mTNiPA.jpg)
           how to press on yellow tool?

or give to buttons and tooltips ITS OWN PLACE (like in blender) where it will not overlap with something...

![image](https://i.imgur.com/XrXLDQc.jpg)

you yourself allow us scale window of program to ~1030x780 but in such scale we CAN NOT use program - because in viewport many buttons and text overlap.

**Comment by Fura123** [comment]
I've tried many versions and I've never seen this. Uninstall the program, go to disk C-User-''Your name''-app data-roaming And delete the Plasticity folder, then install and watch again. To be able to see the app data folder, you have to select (view) on the folder and select (view hidden items).
