### ISSUE TITLE
Obj

### ISSUE THREAD

**Issue by Fura123** [nkallen/plasticity#103]
I hope parasolid's Obj is better than the 0.6.30. Save obj in (MOI) as tri and quad works perfectly in blender, version 0.6.... it doesn't work well when scaling in blender in ''edit mode'' all faces are separated, with Moi it works perfect. Have a good day

**Comment by nkallen** [comment]
Parasolid's is better but it's not as good as moi. however the issue you're describing is just that the faces aren't joined together. which is a fairly easy thing .... in general keeping the faces separate is useful for uv unwrapping. you can just merge by distance and discard normal data for now.

**Comment by Fura123** [comment]
> 

nkallen I have no problem with the separate faces, there are two ways to join them - merge by distance and by an addon that comes in Blender. I wrote more because of newbies who are unaware of certain blender tricks. And for UV I always do it manually with the faces together, otherwise it doesn't look good especially on rounded parts. Here you have a sample of the separate faces, which is a lot :) . Have a nice day, and keep up the good work. Photo:  https://ibb.co/TtQrYbm
