### ISSUE TITLE
about Command line and Python support

### ISSUE THREAD

**Issue by smoluck** [nkallen/plasticity#104]
Hi nkallen

I'm wondering if it's on your plan to have a possible command line mode to let us run Python scripts to process the data out.
it could be awesome and open up a lot of possibilities i think.

[Example of one script i've made for quick Plasticity to Modo workflow](https://youtu.be/pp90-PRTD-A)

Continue the good work on this beast !
Best regards,
Franck

**Comment by nkallen** [comment]
Javascript is planned, not python
