### ISSUE TITLE
Plasticity Logo Proposal

### ISSUE THREAD

**Issue by kaseopea** [nkallen/plasticity#105]
Hi, Nick!
I love your awesome software and want to contribute into project. I can provide design / web services.
Here you can find some logo options for Plasticity. Let me know if you like it.
![plasticity_v1](https://user-images.githubusercontent.com/5718457/192725308-6787cf7f-000f-4267-a927-449aca09ae56.jpg)
![plasticity_v2](https://user-images.githubusercontent.com/5718457/192725313-3917fa8c-d1ac-4268-9d82-3c27216ad8d5.jpg)

**Comment by Fura123** [comment]
As it is a 3D program I preferred this style. Like the fusion 360 symbol. I made an example of an idea. 
![Plasticity](https://user-images.githubusercontent.com/108146633/192832509-423e84ec-de79-4ead-8d66-a9e836e40a97.jpg)

**Comment by Fura123** [comment]
Another idea.  
![Plasticity 2](https://user-images.githubusercontent.com/108146633/192859153-39de7fcc-fb72-461a-88cd-94582023020a.jpg)

**Comment by ato-zen** [comment]
My proposal
![p01](https://user-images.githubusercontent.com/113929474/194855188-980a3114-02d5-4614-952e-08bf932190d8.png)
![p02](https://user-images.githubusercontent.com/113929474/194855193-8b245c38-f000-4033-ad6d-c7a6f2812e6f.png)
![p03](https://user-images.githubusercontent.com/113929474/194855195-4d345198-e2cf-43af-bc1d-11ab7a83e030.png)
![p04](https://user-images.githubusercontent.com/113929474/194855200-4e305389-0ca3-444f-beb6-982889042f45.png)
![p5](https://user-images.githubusercontent.com/113929474/194855205-ea2bb013-a02e-4277-a366-0f6aea5b3159.png)
![p06](https://user-images.githubusercontent.com/113929474/194855209-52814ca0-499c-4b2c-8638-f2332121c50e.png)
![p07](https://user-images.githubusercontent.com/113929474/194855211-7576553c-ebad-4683-85b0-bc3ac1e0111d.png)
![p08](https://user-images.githubusercontent.com/113929474/194855217-c72abb2b-a71d-4d88-a30d-155f0293b107.png)
![p09](https://user-images.githubusercontent.com/113929474/194855222-546eeb5a-da0e-4530-8feb-bc12603e8af4.png)
![p10](https://user-images.githubusercontent.com/113929474/194855224-d6b031ab-8d1b-46c8-91cb-8fd78de4a320.png)
![p11](https://user-images.githubusercontent.com/113929474/194855227-2e5c7ed2-b8b0-4b97-8d1a-7a41bb779ac5.png)
![p12](https://user-images.githubusercontent.com/113929474/194855230-877c61c0-e14d-46f0-b9f3-d3d19d98e901.png)
![p13](https://user-images.githubusercontent.com/113929474/194855236-d40aa7a0-b140-44c0-9b26-621880debae0.png)

**Comment by nkallen** [comment]
Do you guys want to join the discord? That's my primary method of communication

https://discord.gg/4hjA4SnH

**Comment by Fura123** [comment]
![Plasticity Teste iconPNG BOM TRANSPARENTE](https://user-images.githubusercontent.com/108146633/195215327-65880c41-6b08-482c-b2a1-58238928ee8b.png)

**Comment by kaseopea** [comment]
> Do you guys want to join the discord? That's my primary method of communication
> 
> https://discord.gg/4hjA4SnH

I would love to, but it is saying that invitation is invalid\expired. How can I join?

**Comment by nkallen** [comment]
https://discord.gg/BtJUkGfN
