### ISSUE TITLE
Missing object list in Parasolid version

### ISSUE THREAD

**Issue by bmobius** [nkallen/plasticity#107]
While I'm enjoying the updates to the UI, I cannot seem to find out how to make the object list appear. On pervious versions it was on the left side of the screen. Now I've nothing showing at all. Please help?
![PlasticityParaHelp](https://user-images.githubusercontent.com/55331550/193184457-fb2d3bb4-4211-470f-8271-73ea10d75ea2.jpg)

**Comment by Fura123** [comment]
bmobius parasolid is still under construction and is in testing phase, it still doesn't have objects or saves or anything. Nkallen is evolving this version little by little. At the moment only version 0.6.29 has the objects, although it lacks many tools at the moment it is the best you can use.
