### ISSUE TITLE
Maya-style and 3DS Max navigation broken on 0.1.4.2

### ISSUE THREAD

**Issue by bmobius** [nkallen/plasticity#112]
Maya Controls:
Alt + Left Click rotates view as expected.
Alt + Middle Click pans view as expected.
But Alt + Right Click does not correctly zoom view. Zoom seems pushed off to one side of the camera and the zoom action itself seems sporadic and stuttering.

3DS Max Controls also all work as expected with the exception of Zoom (Shift + Alt +Middle Click) which acts as mentioned above for Maya controls.

**Comment by nkallen** [comment]
0.1.44 will have a fix

**Comment by bmobius** [comment]
Thank you!
