### ISSUE TITLE
Maya-style zoom still broken

### ISSUE THREAD

**Issue by bmobius** [nkallen/plasticity#113]
After doing a complete clean install of Plasticity 0.1.44, It seems that the zoom is still bugged. Holding down Alt+Right Click and moving the mouse makes zooming jumpy, overly-sensitive, and tangential to the mouse pointer location. For zooming to act almost as expected, the pointer must be centered in the viewport.

**Comment by nkallen** [comment]
Can you upload a video? I can't reproduce. The zooming is now relative to the cursor, but there is no jumpiness that I see

**Comment by bmobius** [comment]
I currently do not have a video capture app of any kind. What I'm looking for is for the same camera behavior as what you would get in Blender if you set Keymaps to "Industry Standard" in Blender Preferences. It's the same behavior found in other apps as well. Such as Marmoset Toolbag, Quixel Mixer, ArmorPaint, and so on. Basically, zoom is constrained to moving along the camera's direction (Z-Axis in Blender, Transformation Orientation set to local). Only moving the mouse up and down zooms the camera, not left or right. In Plasticity, zooming (Alt+Right Click) while moving the mouse up and down does zoom, but any slight movement to the left or right causes the camera to zoom in and out in an unpredictable fashion.

The way camera movement worked in the previous version of Plasticity (Pre-Parasolid) when Orbit was set to Maya worked as expected.

**Comment by nkallen** [comment]
I believe blender by default, is left-right to zoom in and out, not up down. There's literally no way to satisfy everyone with this stuff :(

**Comment by bmobius** [comment]
Blender 3.x default zoom is Ctrl + Middle Click. Mouse movement for zooming is locked to up and down (x-axis?). Moving the mouse left or right has no effect on zooming.

Additionally, the default zoom in Blender 3.x is constrained to the camera's local z-axis instead of Plasticity's mouse pointer position. The benefit of this is that the viewport zooms with the same consistent behavior, regardless of the mouse pointer's location. This prevents the user from having to place the pointer in the exact center of the viewport when they wish to zoom along the camera's local z-axis.

This is the same kind of viewport/camera navigation you find in almost every major 3D modeling and texturing application.

That said, thanks for hearing me out. Perhaps you could include a ways for users to create their own mouse and keymap settings in the future.

Thanks for all you do!

**Comment by bmobius** [comment]
Is that for the 0.1.49 release?

**Comment by nkallen** [comment]
Yes I'll add that next week

**Comment by nkallen** [comment]
Next release:
```
{
    OrbitControls: {
        zoomToCursor: false,
        zoomVertical: true,
    }
}
```

**Comment by bmobius** [comment]
That is perfect! Nick, you really do a fantastic job of addressing issues and listening to your users. Plasticity will be a day one purchase for me if for no other reason than you being a great developer who listens to their community.

With this update and your assistance with the above script, Maya orbit now works exactly the same as many other professional apps. It's going to be a breeze to create something in Plasticity and export it out to other applications without the worry of changing orbit control schemes. I cannot thank you enough!

**Comment by nkallen** [comment]
Please join the discord https://discord.gg/asmFU9Jw 

I prefer it to GitHub
