### ISSUE TITLE
Question: C3D alternative

### ISSUE THREAD

**Issue by nine-fox** [nkallen/plasticity#114]
Hi, 

No worries, this is just a QA issue :-)

I just found this project is so cool and it is amazing to create shapes with it - the functionalities are almost the same as bigger software like Solidworks and fusion 360. You are doing a great job! Looking for the release version.

After some days investigation, I just found compile this project will need a commercial software - c3d. Well, due to limited money, I am looking for the 3d alternative libraries. Just a question, would you think it is achievable goal to replace c3d with OpenCascade? Since Opencascade is free to use and that's only alternative CAD library I can found from github.

So how would you suggest if I use OpenCascade to develop the same project with the same functionality? Thanks!

Thanks,
Vincent

**Comment by nkallen** [comment]
OpenCascade does not really support direct editing, so it's not really an option
