### ISSUE TITLE
Unit system

### ISSUE THREAD

**Issue by Elguajo** [nkallen/plasticity#115]
I don't understand in any way what unit of measurement plasticity uses? 
For example, in Moi3d, you can configure the system of units 
https://imgur.com/a/MZXXvRp

Is it possible to implement such functionality in Plasticity?

**Comment by nkallen** [comment]
Plasticity is unitless. In reality all CAD programs are unitless and the units are just a user interface convenience. Most users find this very confusing so eventually plasticity will have units and they will be meters by default, like blender. If you're importing into MoI I would recommend settings the units to meters or unitless.
