### ISSUE TITLE
can't Snap on Grid

### ISSUE THREAD

**Issue by KondouYu** [nkallen/plasticity#116]
Hello! Grid snaping Can't Working.

**Comment by virtualritz** [comment]
`0.9.9`: I noticed grid snapping, when turned on while creating/constructing a primtive, isn't considered.

One has to cancel the operation and start it again and the snap works.

Not sure if this is what OP meant. I would think it more intutive/user friendly if construction constraints can be switched on/off freely while creating/constructing something.

**Comment by enzyme69** [comment]
I reckon that Plasticity could take a look at "Grid Modeler" addon from Kushiro, a more flexible and easy to use Grid implementation. Especially great when doing "box booleans" on parasolid.
