### ISSUE TITLE
Bevel Handles not appearing in Windows.

### ISSUE THREAD

**Issue by ajk2196** [nkallen/plasticity#117]
Here is my file. As you can see, there are no handles for beveling the rectangle/curve.
![Screenshot (108)](https://user-images.githubusercontent.com/90527174/216806690-df4786c3-60f7-4bc4-bb18-eb5514003979.png)

Here is a screenshot from a Youtube video. The handles for bevelling are appearing in this Video.
![Screenshot (107)](https://user-images.githubusercontent.com/90527174/216806704-41a55263-7926-443c-894a-774f40542f56.png)

**Comment by nkallen** [comment]
you can bevel vertices and curves with the 'b' keybinding. The interface has evolved a bit
