### ISSUE TITLE
Support trimmed NURBS in OBJ export

### ISSUE THREAD

**Issue by virtualritz** [nkallen/plasticity#120]
It would be great if the OBJ export could alternatively contain the (trimmed) NURB surfaces from the b-rep.

Few people today know this but Waveront OBJ is [perfectly capable of storing these](http://paulbourke.net/dataformats/obj/) (scroll down to **Free-form curve and surface types**).

Among the apps that ingest OBJs containing higher order geometry are Maya and Rhinoceros 3D. The data stays trimmed NURBS in the apps; i.e. is never tessellated into polygons.

I am also working on an OBJ importer for Houdini that support OBJs containing this sort of geometry.

**Comment by nkallen** [comment]
Sorry I'm not going to implement this. STEP is the only decent open nurbs format. The studio version will have direct rhino export for those interested

**Comment by virtualritz** [comment]
People doing visualization in Maya will have trouble with STEP (or IGES).
I'm speaking from obver 20 years experience with this scenario.
I motly went/had to go STEP/IGES->Rhino->OBJ->Maya to get NURBS data cleanly/completely/w/o issues into that app.

Certainly, until you have paying customers who want to need an inroad to Maya this is unimportant. But I'd keep that in mind (and maybe the issue open). :)
