### ISSUE TITLE
[FEATURE REQUEST] Add Functionality to modify the shortcuts used to utilize / activate various commands.

### ISSUE THREAD

**Issue by ajk2196** [nkallen/plasticity#123]
Adding a feature to modify the shortcuts of the commands used will do three things:

1. Prevent future requests to change shortcuts as users themselves will have control of the shortcuts.
2. Will add user-friendliness for every individual who comes from different CAD software learning backgrounds.
3. Will speed up workflow for the ones who are hotkeys oriented - like users of Blender 3D.

Assigning keyboard shortcuts should be easily accessible by right-clicking on the command in the 'F' menu.
Importantly, the access to the menu called by pressing the 'F' key should be changed to be called by clicking the right-click.

This does not require assigning hotkeys/keyboard shortcuts to all the non-assigned commands.
Also, there must be an option to reset the hotkeys to default.

**Comment by nkallen** [comment]
Feel free to add feature requests to http://plasticity.canny.io
