### ISSUE TITLE
Proposal to shorten workflow to move, scale and rotate an object.

### ISSUE THREAD

**Issue by ajk2196** [nkallen/plasticity#124]
Moving and rotating are going to be used extensively in designing workflows. Therefore, I think that their workflow can be shortened. Since both's workflows can be shortened, I think that scaling too should be taken along and worked upon.

Here's my proposal on how to make it work:

After selecting an object, pressing 'G' activates the function to move, and the gizmo of three axes.
Upon clicking on an axis, a dialog box should or should not pop up, but we should be able to type in a number and upon pressing 'Enter' after typing the number, the object should move that many units in the direction of the clicked-upon axis. Upon pressing 'Alt+Enter', the object should move along the selected axis in the negative direction.

The same goes for Rotation and Scaling. This will give a better hold on parametrically creating/changing the design.

**Comment by nkallen** [comment]
You can type "gx1<enter>"  to move 1 unit along x, just as in blender. 

Feel free to add feature requests to http://plasticity.canny.io
