### ISSUE TITLE
Proposal to mention units everywhere by default.

### ISSUE THREAD

**Issue by ajk2196** [nkallen/plasticity#125]
All dialog boxes should have units mentioned.
It does not necessarily need to be mentioned after every input field in the dialog box.
For ratios or non-unitary numbers in the dialog box, a different color should be used in the background of the input field to indicate the number to be ratio or non-unitary.
Just adding something like 'units are in mm' or 'units are in millimeters' using noticeable font size and color will do the job.
However, when carrying out operations like bevelling/chamfering/filleting in the viewport by dragging the handles, the units must be mentioned beside the number in the viewport.

**Comment by nkallen** [comment]
Feel free to add feature requests to http://plasticity.canny.io
