### ISSUE TITLE
[Feature Request] Add a feature to assign the type of material to an object.

### ISSUE THREAD

**Issue by ajk2196** [nkallen/plasticity#126]
This is a lot different from the materials in the context of shading. Here, I mean a list of real-life materials with their characteristics like density to be available by default. The objects in the project can be assigned their materials and based on their volume, the users should be able to see the exact weight of the selected object, along with the exact weight of all the objects combined. Also, there must be an option available in the list to add a custom material with custom parameters. Units of weight too should be indicated along with. This feature will be a lot useful when working with 3D printing.

**Comment by nkallen** [comment]
Feel free to add feature requests to http://plasticity.canny.io
