### ISSUE TITLE
Image planes change their order or don't work at all after restart

### ISSUE THREAD

**Issue by Fuso1505** [nkallen/plasticity#129]
Placing reference images works well until I restart Plasticity. I drag&drop them to viewport from folder in which I keep bunch images.
After restarting program images change their order (they appear in place of they are different images) or display plasticity logo.
Windows 10, Plasticity 0.8.10 but it also appeared on e.g. 0.8.6
![image](https://user-images.githubusercontent.com/83554183/221410688-b0b1de86-970f-4db5-8676-cc3040cc104d.png)
![image](https://user-images.githubusercontent.com/83554183/221410717-07d251ec-6b19-4a7c-a47c-9f83e3ee29aa.png)

**Comment by nkallen** [comment]
At the moment plasticity just keeps a reference to a file, so if you move your image file or move your .plasticity file, the link can be broken. At some point I will probably embed image data in the .plasticity file, but not super soon

**Comment by Fuso1505** [comment]
@nkallen 
The problem is that even if I create completely new scene, import reference image, then save, close and reopen it doesn't work.
I didn't change the location of either the .plasticity file or the photos 
It may work with one image but if I add more of them it breaks
![plasticity references issue](https://user-images.githubusercontent.com/83554183/222918466-12439331-e3a8-4f73-9ab9-f9094d74c01d.jpg)
