### ISSUE TITLE
The installer goes into an endless loop.

### ISSUE THREAD

**Issue by krasnovpro** [nkallen/plasticity#130]
Any last versions (plasticity-beta-0.8.11.Setup.exe).
![1](https://user-images.githubusercontent.com/886676/221708231-99f5a801-0c79-4ce9-bdb9-dc7d38488c2a.gif)

**Comment by ishii84** [comment]
Running into the same issue 
![image](https://user-images.githubusercontent.com/130187786/230683418-0daec22a-25eb-4cf2-81f7-59e9e4763d44.png)
