### ISSUE TITLE
I see some c++ code that is not open source

### ISSUE THREAD

**Issue by breakerrorchen** [nkallen/plasticity#131]
I see some c++ code that is not open source,

Is the geometry engine open source or self-developed? If it is an open source project, which project is it based on (curious)?

**Comment by nkallen** [comment]
The geometry kernel is Parasolid, though I was using c3d previously

**Comment by jellychen** [comment]
> The geometry kernel is Parasolid, though I was using c3d previously

How much does the Parasolid business license cost
