### ISSUE TITLE
Can you add a blender-like viewing method to the rotation view?

### ISSUE THREAD

**Issue by geiniyiquan250** [nkallen/plasticity#132]
Similar to Orbit Around Selection, or rotate the observation view around the mouse to better observe the model details instead of the view flying around，The current mobile view makes me feel a little irregular, I always go to other places, it is difficult to observe the position I want to see (where the mouse falls)

**Comment by Waffle1434** [comment]
In addition, Blender uses `Alt+MMB` to center the screen on the mouse and set the orbit point.

**Comment by shin-kamui** [comment]
would really like to see a rotate around selection.   Things get weird when working at MM scale for 3d printable objects and i switch between a cardinal view and start free rotating.
