### ISSUE TITLE
How much is the total cost of the geometric engine used by this tool and commercial authorization?

### ISSUE THREAD

**Issue by jellychen** [nkallen/plasticity#133]
How much is the total cost of the geometric engine used by this tool and commercial authorization? 

Can we donate or crowdfunding this part

**Comment by gjsman** [comment]
It's Siemens Parasolid. Very common geometric engine used by dozens of 3D modeling tools from over 130 companies. Even big ones like OnShape, Solid Edge, NX, and SolidWorks are based on Parasolid.

There is absolutely no way they are interested in a lump sum of cash for permanent unlimited use, let alone open-source use. It would destroy the business model of Parasolid, which is a royalty per sale.

**Comment by 0z3l07** [comment]
Buy a studio license for plasticity ;)
