### ISSUE TITLE
Custom shortcut key problem

### ISSUE THREAD

**Issue by iamaweiawei** [nkallen/plasticity#137]
Experience the use of your development software, feel great, like it, get used to it quickly, I tried to modify the keyboard shortcuts, some of the keyboard shortcuts can be modified, but some of the keyboard shortcuts with other fixed keys, i don't seem to be able to find any changes. I'd like to ask if some fixed buttons support custom changes. For example: Y axic is press Y, I want to change other keys to make it easier for me to press this command.

**Comment by rajq123** [comment]
apart from developer i will suggest using "autohotkey" to swap any keystroke and after sometime if it is necessary in your workflow then ask the developer again or you can happy using autohotkey. it is actually a very painful to change hotkey in different program so my ultimate solution is autohotkey.
