### ISSUE TITLE
Need Support for Text Curve and Font

### ISSUE THREAD

**Issue by enzyme69** [nkallen/plasticity#139]
I've been using Plasticity for few days now, currently still using 30 days trial.

Before committing to full indie license, I am actually wondering about interchange-ability of artworks between Blender and Plasticity. Let's say I like to bring in 3D Curve to project inside Plasticity.... how is this actually works?

Overall feedbacks: I love Plasticity and definitely would work awesome if I could go back and forth between Blender + GeometryNodes + BoxCutter/GridModeler + RandomFlow!

**Comment by enzyme69** [comment]
More questions: 
- Also I could not figure out a quick way to Extrude Along Normal. 
- I would like to see Grid and quickly do Array Cut using Lines and in Circular ways like GridModeler, but also I could not figure this out to do it in one go.

**Comment by KondouYu** [comment]
hope suppurt svg file import.
