### ISSUE TITLE
File Dialogues "pop under"

### ISSUE THREAD

**Issue by SteffenDuenner** [nkallen/plasticity#148]
Hi there, I'm using Plasticity under Linux (Mint 21.1, Cinnamon) and all file browsers / dialogues open "under" the main interface.
While running in fullscreen mode I first thought nothing happens when I click on e.g. import/append, but then I noticed that several file browsers were open in the background already.

https://user-images.githubusercontent.com/33224667/232015753-343f7ce8-4820-4151-b884-8e9cbeb97826.mp4

I guess this only happens in Linux?

**Comment by SteffenDuenner** [comment]
Awesome! Thanks :)

**Comment by nkallen** [comment]
Unfortunately this is outside of my hands at the moment https://github.com/electron/electron/issues/32857
