### ISSUE TITLE
exported OBJ will cause an error at import in PrusaSlicer

### ISSUE THREAD

**Issue by kal60** [nkallen/plasticity#150]
I set the units in preferences to mm.
when I export an object to an OBJ-file and import this in the slicer PrusaSlicer I get the warning:
"The dimension of the object seems to be in meter ..."
Does the exported OBJ-file includes the units I set up in preferences ?

running plastcity under Ubuntu 22.04.LTS

**Comment by jeremiah-k** [comment]
Sadly, I don't think you will receive an answer on anything FDM related. See this conversation.
![9e8abda9-774d-4b04-a3a2-64e9b029b309](https://user-images.githubusercontent.com/17190268/232551521-2b08a978-8f22-46d5-8e36-5c06df8b21dc.png)

**Comment by kal60** [comment]
Hi!
Thanks for the info, hopefully I'll have more luck ;-)
I'm not asking for STL, PrusaSlicer can import OBJ and even STEP. Since I'm still using the test-version of plasticity for evaluation, STEP is not available. If I want to work with objects created by plastuicity I think it's neccessary to get the right size of an object. So if the PrusaSlicer can't get the right unit it could be caused by he exporting prigram or PrusaSlicer. Tod be explored :-)
Anyway, it's a question if the units defined in the parameter settings are only for displaying or if the units are stored in the OBJ_file and if so, wheather they are stored correctly. I was also searching for a kind of inspector or some definitions about OBJ-files but hadn't had time to check this.
Meanwhile I also got the Info, that using canny.io would be a better place to place these requests and errors. Also: had't had time yet to pass my post here over to it.

**Comment by Fairlight8** [comment]
I don't know if the main developer of Plasticity cares about the 3D printing community or not, but there is no need to be this hostile.

If we have the ability to export OBJ and STEP, most slicers will be able to import them and use them for 3D printing. It's not like he needs to work on exporting to FDM. However, if the units are not included or the mesh is corrupt, that's something we have to communicate and probably he will solve the bug.

That said. A friend who is using Plasticity now exported some designs in OBJ and STEP and I was able to print them with PrusaSlicer without an issue.

**Comment by kal60** [comment]
Hi
Sorry, I didn't ment to be unfriendly in any way if I might left this image. I appreciate the work very much and I think it's a amazing (big) "piece" of software. I'm still in the mode of evaluating (with the unpaid version).
I just wanted to inform, that I've noticed this when importing an OBJ (not STL) to PrusaSlicer. Good to hear, that it worked well in your env. That information is what I wanted (or another , that the OBJ-file wasn't written mit right units :-) )
I think OBJ is not only used for FDM, right ? So if this is an export-error it might influence an import into other CAD-systems as well. So I only wanted to check, if it's an error in the OBJ-file or something else (that than I've to analyse cause it's not the problem of plasticitiy).

**Comment by Fairlight8** [comment]
No, no, you are perfectly fine, in my opinion! It was about the other picture.

About dimensions. I don't remember, but maybe weren't properly set, that's possible. I didn't do the object, I asked my friend to export it, so I don't know. But if the dimensions are wrong, I am sure that can be solved if we give him time.

**Comment by kal60** [comment]
Oh, ok. Fine :-)
Time ? Huu - if you got some left, I'll take it ;-D I'm in the opinion that every developer / -team who creates such a complex software "just for fun" (i.e. not because somebody told him / them to do it but because he /they think it's time to create a good new software) should "have the right" to define the prio to implement something by him- / themselves - ok, maybe inspired by some votings :-) . And it should be given time to let the app "growing" ...
Again: I think Nick (and are there co-developers)  made a great job !

Back to the topic:
I will do some more investigation. Didn't had the chance to inspect the OBJ-file yet. I also will send the file to a friend who do know much more about CAD than me, he will check the OBJ-file as well so I hopefully can give more information.
Anyway it's not a big problem cause PrusaSlicer gives a warning and suggests to correct the unit from meter to mm, so ...;-)

Will be back with some more infos later ..

**Comment by kal60** [comment]
OK, I got it now. Just a little bit of googling ;-)

Wikipedia: _Wavefront-OBJ-Files are unitless, a human readable comment can be added (I doubt, that PrusaSlicer can read that cause it may be of any format)_

So the "native" unit for plasticity seems to be meter and the exported OBJ-files apply to that unit.
The exspected units for PrusaSlicer is obviously mm, that's it.

**So all is right with the export**. 

I'll will have a look, if I can "force" PrusaSlicer to use  the right units, otherwise I'll live with the warning.

Thanks for your informations.
