### ISSUE TITLE
Window goes blank almost immediately

### ISSUE THREAD

**Issue by kscarlett** [nkallen/plasticity#154]
I have just installed v1.0.11, and as soon as I do a few operations, the window goes blank and the application has to be closed.

This is pretty much a clean install, and I'm not doing anything special, so I'm not sure there's anything specific that needs to be done to reproduce this. I have verified with the previous version that is available (1.0.5), and that version works fine.

This is on Windows 11. If there's any log files anywhere that I can attach, please to tell me.

https://user-images.githubusercontent.com/7826443/232326756-285521bd-0ca0-4a08-8b8b-3b9f2f9f0a07.mp4

**Comment by nkallen** [comment]
Hi, I had a problem with the windows build; please reinstall 1.0.11

**Comment by ABWhiskey** [comment]
Hello,

I installed the latest version today (1.0.11) and also had the same problem. I'm on win11 with all the updates up to date (system and drivers).

**Comment by evilactually** [comment]
Same problem here on Linux. 
Linux vlsh-Q505UAR 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nkallen** [comment]
For those on windows  - Please redownload latest 1.0.11 — it was rebuilt. 

Linux requires Ubuntu 22
