### ISSUE TITLE
Reverse engineering - just a feature request

### ISSUE THREAD

**Issue by csabal** [nkallen/plasticity#160]
Hi! Is there any plan to include reverse engineering features? For example import a mesh file, and make a CAD version of it.  
Siemens Parasolid is very good for that as well! I don't think it is a very hard to implement it actually.... 

Anyway, I gonna support your hard work, and buy the Studio license! I am sooo tired of Fusion, Solidworks, Inventor etc. etc. etc. eh.

**Comment by ericjeker** [comment]
Hi @csabal, you can do feature requests here: https://plasticity.canny.io/feature-requests
