### ISSUE TITLE
Node-Locking clearly making problems

### ISSUE THREAD

**Issue by hasechris** [nkallen/plasticity#162]
Hi,

i wanted to try your software; because FreeCAD is just too painfull and i really dont want to use Fusion 360 in my Windows VM, that also hurts but i have to. I'm on Manjaro Linux (directly on Hardware, not in VM or Container or something) and sadly i triggered your node-locking code with just 15 minutes of testing.

What i did:
- Installed 1.0.12 via Pacman AUR [0]
- Tried it (sadly the gpu acceleratio did not work. 120 FPS on FPS Counter when doing nothing; 0-2 FPS when just click-dragging and 100% CPU but no GPU Load)
- Removed the package
- Removed the folder ~/.config/Plasticity
- Removed the folder ~/.plasticity
- Installed 1.0.16-beta via Pacman AUR [0]
- Opened it --> Node-Locking complaining that the trail has run out (ON THE FRICKING SAME DAY...sorry)

The following is just my opinion, i hope i dont offend you in any way.
Node-Locking is a really bad idea and just does not solve the problem you try to solve with node-locking.
- Mac Address matching or 
- doing some magic bullshit to identify a PC (Microsoft!?) is just not going to work reliably. 
- Also Hardware IDs (like from SystemD) might also change on Distribution Upgrade. 
- Also if the app will run in an AppImage in the future there will not be reliable systems to identify the system, because AppImage, Flatpak and the rest of these systems are specificly designed to sandbox and isolate apps from the system and vice versa.
- Also if you go out of business, are not reachable or maybe my "help" cries just land in your spamfolder and my PC died i cant use the rightfully bought software on another computer because maybe i tripped the node-locking code just one time to often.

So to summarize: You give a software paket to me. I gave you the amount of money you charge. You still have to trust me that i wont be using the software on more computers that you allowed me, because it is just not possible for you to reliably lock that down to the right PC without creating big problems for the majority of users. That is not changing with a "magic node-identifying piece of code". The technerds will always figure out your code and just plainly ignore it or get around it. That is really not hard. Just look at the vgpu-unlock code which tricks nvidia enterprise code to run on normal Geforce GPUs instead of their enterprise lineup. Why is it working? Because we just spoof the pcie vendor and product id.

Please, just step back just one step in your mind and look critically at that piece of your software again.

![image](https://user-images.githubusercontent.com/16565473/233866411-0edc7f7d-f2fb-405d-9f8d-d81d10f6f0cd.png)

My OS: Manjaro

[0] https://aur.archlinux.org/packages/plasticity-bin

Greetings
hasechris

**Comment by nkallen** [comment]
I appreciate your feedback but "please have zero piracy protection" is not realistic.

FWIW, Ubuntu 22 is the only supported linux and all beta releases (e.g., 1.0.16) are for Studio licenses only
