### ISSUE TITLE
Scaling faces acts unreliably

### ISSUE THREAD

**Issue by samallman87** [nkallen/plasticity#174]
Scaling faces has been really finnicky for me. When trying some pretty basic transformations the scale tool acts as if it's working however the selected face remains untransformed. Sometimes it works fine, sometimes it doesn't. I have not been able to tell under what circumstances one might predict it to be successful or fail. I've included a short gif to hopefully illustrate this better.

Similarly, though I'm not sure if this is intended behavior or not, but I am unable to use the scale tool at all when selecting the edges of the same face in the video 

![2023-05-11_18-53-45 (1)](https://github.com/nkallen/plasticity/assets/35620673/4b6d7b90-f63c-40e3-8a80-a3b1e81eee4c)

**Comment by nkallen** [comment]
Scaling faces scales the surface, so this is behaving as intended
