### ISSUE TITLE
enhancement idea: Line Alignment

### ISSUE THREAD

**Issue by Peeko910** [nkallen/plasticity#177]
enhancement idea, line alignment:

I am a student and in my university teaches alias autodesk, in that app the ''Align'' tool is fundamental to create smooth surfaces and complicated patterns. I think that if there was an ''align'' tool in plasticity it would be more than amazing. (so aligning the directiong and torsion of the curve so it is able to be used to create a curve that connects perfectly with another one) Unless i didnt see it already? (i know you can create curves and stitch them together to form a similar thing to an aligned curve, but if it was easier and cleaner it would revoluzionize the usage of plasticity!!!

All the people who come from Alias would buy plasticity as a cheaper and overral better app. 

also, must say, the fact that the app only crashed 1 time in 1 month and it always ''autosave'' the file you have open, makes the app a legit professional grade tool

video of alias autodesk with its align tool:

https://github.com/nkallen/plasticity/assets/133853708/1e1f1395-c65f-461f-a85b-b3e775f427e4

**Comment by Fairlight8** [comment]
I would propose this in plasticity.canny.io

**Comment by nkallen** [comment]
Aligning curves is very easy, fortunately. Aligning surfaces is extremely extremely difficult. Hopefully I will support that for version 2.0 but it's hard to know for sure

**Comment by nkallen** [comment]
But yes, use canny
