### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CoreyCorza** [nkallen/plasticity#18]
Can you please add options to change navigation shortcuts? Pretty please :)
I use middle click pan :'( 
Love it so far. Apart from the navigation thing :)

**Comment by attahiruj** [comment]
you can use X-mouse button to remap your controls in the meantime.

**Comment by CoreyCorza** [comment]
My mouse doesn't have an X button?

**Comment by CoreyCorza** [comment]
Also, the navigation pivot point is hard to handle. It seems to just do its own thing and sometimes the viewport is just pivoting around some point 50meters away from the model. 
Be nice if it "focused" on the last selected thing and rotated around that or something

**Comment by nkallen** [comment]
You can customize the keybindings for navigation... In general it's better to ask for support on discord

**Comment by attahiruj** [comment]
> 

you can focus on an object by selecting it and pressing the / key. the rotation will be about the origin of selected object.

**Comment by attahiruj** [comment]
> You can customize the keybindings for navigation... In general it's better to ask for support on discord

can you please share the discord server link. thanks.

**Comment by CoreyCorza** [comment]
> 
I don't see any options to customize keybindings for navigation and Ive sent an email about joinging the discord but haven't received any reply

**Comment by mossbros** [comment]
Seeing as no one pointed in the right direction 
AppData\Local\ispace\app-0.5.12\resources\app\.webpack\main\dot-plasticity 
Editing the keymap.json file should enable you to change the controls, but it doesn't work after reloading the software. 

Really would appreciate some in app UI to enable this as can make or break fluidity in a software.

**Comment by nkallen** [comment]
It's in c:\users\myusername\.plasticity\keymap.json

**Comment by skarkkai** [comment]
Coming from Blender, I really miss setting pivot point by clicking alt + middle click. That said in Blender it's poor UI that alt + middle click sets pivot while alt + middle drag rotates viewport; it's easy to rotate by mistake when you wanted to set pivot. Something like setting pivot point with ctrl + middle click would be great though.
