### ISSUE TITLE
Cannot get demo license because of "You're not connected to internet ERR_INTERNET_DISCONNECTED" error

### ISSUE THREAD

**Issue by gaaldornik** [nkallen/plasticity#180]
How to solve this? Tried in macOS and Windows, results are exactly the same.

**Comment by 2chhk** [comment]
Use a proxy server in Windows settings or VPN.

**Comment by gaaldornik** [comment]
It worked, thanks!

**Comment by band44** [comment]
> Use a proxy server in Windows settings or VPN.

Can you show exactly how to do this, pls?

**Comment by gaaldornik** [comment]
I've installed the free app ClearVPN.
