### ISSUE TITLE
Grid too bright since v1.1.27 ?

### ISSUE THREAD

**Issue by ABWhiskey** [nkallen/plasticity#185]
Hello,

Since version 1.1.27, the grid (white line) is much too visible, too bright. It keeps me from concentrating on the 3D shape.

I deleted the configuration files in order to restart "like new", but the same, they are still as bright. Of course, I can remove the grid, but he also removes the axes, which doesn't help me.

A way to solve this problem ?

Thanks.

**Comment by kaseopea** [comment]
Joining the club) Switched back to 1.1.26 due to the grid brightness.

**Comment by ABWhiskey** [comment]
This seems to be corrected with the latest version (1.1.29), at least on my side.
