### ISSUE TITLE
Feature: Click through face

### ISSUE THREAD

**Issue by gitlisk** [nkallen/plasticity#193]
Problem: Selecting a face that is hidden behind another.
Solution: Ignore first hit and provide the user with the next hit.

Possible bindings:
Modifier + mouse button
Double click if Selection Mode Face is activated.

Is there a way that does not require rotation?

**Comment by wavetro** [comment]
It looks like this is a [planned feature](https://plasticity.canny.io/feature-requests/p/selection-window) according to Plasticity's feature request website

**Comment by gitlisk** [comment]
was not aware of the website. thanks.
