### ISSUE TITLE
Feature: Select all in group

### ISSUE THREAD

**Issue by Flavius-Geani** [nkallen/plasticity#195]
Problem: Selecting items in a group requires many steps.

User journey: I want to select all items.
- navigate with the mouse to the group 
- click the " > " to expand
  - it is a precision act
  - it has dead space all around it 
- click the first item
- shift
- click the last item

Streamlined:
- navigate with the mouse to the group
- right click or modifier + click

Context: item is selected and in a group
- Command to select all items in group

**Comment by nkallen** [comment]
alt-clicking on the group will select all its children
