### ISSUE TITLE
Bug: "Navigation preset" will select Fusion360 or Rhino and they will both be selected.

### ISSUE THREAD

**Issue by ktyubeshi** [nkallen/plasticity#197]
### Environment

* Windows 11
* Version: 1.2.0

### Issue
"Navigation preset" will select Fusion360 or Rhino and they will both be selected.
![image](https://github.com/nkallen/plasticity/assets/1130122/76012ef6-a01d-4103-b89a-3676c4bc833a)

**Comment by nkallen** [comment]
1.2.x
