### ISSUE TITLE
Bug/Performance: Draft solid weird behaviour

### ISSUE THREAD

**Issue by 0z3l07** [nkallen/plasticity#2]
See the video

https://user-images.githubusercontent.com/24977832/135915685-76db1c58-36cd-40a9-a80d-c1f6ebcdf10c.mp4

**Comment by nkallen** [comment]
yeah that's weird... it's rotating the wrong face

**Comment by 0z3l07** [comment]
And its also adjusting different each time. Sometimes higher or lower
