### ISSUE TITLE
Wavefront OBJ Export does not produce .obj file

### ISSUE THREAD

**Issue by Nocxr** [nkallen/plasticity#22]
Just downloaded 0.5.12 release to try out plasticity (liking it so far btw!) and attempted to export a model as an .obj unsuccessfully.  The window closes and appears like it was successful, but nothing else shows up and no file is created.  I tried the other 4 formats and confirmed those are creating files, .obj is the only one that seems to not work.  I did try restarting and also different locations and that did not fix the issue.  See below for what I see on my end:

https://user-images.githubusercontent.com/72276215/156787671-b01307c4-e140-4563-b51c-d2b5d1bc9e08.mp4

Windows 10 21H2

**Comment by nkallen** [comment]
Try selecting the objects you want to export

**Comment by notthewave** [comment]
Maybe prompt the user to select an object before exporting.
