### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by zohozer** [nkallen/plasticity#23]
I just discovered this project and I am interested on using this software on a Linux machine. Any chance to see a Linux build?

**Comment by nkallen** [comment]
Linux is always one version behind the latest

**Comment by Critical11** [comment]
What about a Mac version

**Comment by VuiMuich** [comment]
> Linux is always one version behind the latest

May I ask for the reasoning? Are the builds taking too much resources?

**Comment by zohozer** [comment]
Thank you. I checked only the latest build but as I can see there is a Linux and Mac version in earlier builds.
