### ISSUE TITLE
Radial array not defining axis

### ISSUE THREAD

**Issue by mossbros** [nkallen/plasticity#24]
When using radial array with an object such as a box, if you'd like it to follow an axis it seems to not work as expected unless done in orthographic. 
When using orthographic view it works on the expected axis, but because you can't choose an axis it doesn't utilize the correct one a lot of the time in standard view.

### Perspective view
![Radial array Perspective](https://i.imgur.com/ZUm7gWX.gif)
![Radial array2 Perspective](https://i.imgur.com/PbWFr97.gif)

### Orthographic view
![Radial array3 Orthographic](https://i.imgur.com/XaZriPh.gif)

**Comment by nkallen** [comment]
I agree, I'll add it to the list. In general, however, I'm not responding to GitHub Issues yet. Discord is the primary way of interacting with me
