### ISSUE TITLE
Fr: Way of slowing down movements

### ISSUE THREAD

**Issue by 0z3l07** [nkallen/plasticity#3]
Sometimes to movements of faces are quite fast or erratic. Maybe a system where you can increase/decrease increments or slowing down the action can be beneficial maybe

**Comment by nkallen** [comment]
Which specific command do you have in mind (so I can try it there first)? I'll probably do something where SHIFT is 10x faster and alt is 0.1x as fast

**Comment by 0z3l07** [comment]
Yeah shift and ctrl I had in mind but only active when in movement adjusting mode. But maybe you want to reserve those for snapping or free movement like shift is atm

**Comment by nkallen** [comment]
what do you mean "movement adjusting mode"? do you mean during the move command? or do you mean commands like fillet?
