### ISSUE TITLE
compilation instructions for Linux

### ISSUE THREAD

**Issue by Sinasta** [nkallen/plasticity#30]
Thank you for your work. i want to ask if you could add compilation instructions for Linux?

**Comment by nkallen** [comment]
You ABSOLUTELY do not have permission to redistribute binaries

**Comment by Techwizz-somboo** [comment]
> You ABSOLUTELY do not have permission to redistribute binaries

I'm not going to redistribute your binaries. It will download the package from your offical deb in releases.

**Comment by LucyDemooon** [comment]
instead of .deb or .rpm you can pakage it to .appimage this works on all linux distributions + all dependencies are in it.
https://appimage.org/

**Comment by Techwizz-somboo** [comment]
> instead of .deb or .rpm you can pakage it to .appimage this works on all linux distributions + all dependencies are in it. https://appimage.org/

I second this, it's the best method.

**Comment by dumblob** [comment]
@Techwizz-somboo do you still plan an AUR package? I'd be interested in that :wink:.

**Comment by MincingWords** [comment]
I've cloned the repo onto an Arch Linux machine. I'm used to getting hold of source trees and building apps from them but I'm finding nothing here that I know what to do with. The README.md file is uninformative.

**Comment by Techwizz-somboo** [comment]
> @Techwizz-somboo do you still plan an AUR package? I'd be interested in that 😉.

Yes! I'm almost done with it but I don't have a ton of time to mess with it. A lot is going on in my life right now. 

@MincingWords You can't build it. It requires a closed souced library. It will be provided when you buy Plasticity. Also the way I'm doing it is by converting the deb to an arch package.

**Comment by jvanstraten** [comment]
For anyone on an Arch-based system stumbling into this before this makes it to AUR, this worked for me:

 - Make a file named `PKGBUILD` in an otherwise empty directory:
   ```sh
   pkgname="plasticity-bin"
   pkgver="0.5.32"
   pkgrel="1"
   pkgdesc="Plasticity beta"
   arch=("x86_64")

   source=("https://github.com/nkallen/plasticity/releases/download/v0.5.32/plasticity_0.5.32_amd64.deb")
   sha256sums=("530495bbaef5cbdd1346e54801d1dfa770078125074c681c4aee14917332d523")

   package() {
     cp -r "$srcdir/usr" -t "$pkgdir"
   }
   ```
 - Run `makepkg` to build the package.
 - Run `sudo pacman -U plasticity-bin-*.pkg.*` to install.

To update it:
 - change `source` to the newer github release URL;
 - change `pkgver` accordingly;
 - update the checksum or set it to `SKIP` if you can't be bothered computing it.

**Comment by Techwizz-somboo** [comment]
> For anyone on an Arch-based system stumbling into this before this makes it to AUR, this worked for me:
> 
>     * Make a file named `PKGBUILD` in an otherwise empty directory:
>       ```shell
>       pkgname="plasticity-bin"
>       pkgver="0.5.32"
>       pkgrel="1"
>       pkgdesc="Plasticity beta"
>       arch=("x86_64")
>       
>       source=("https://github.com/nkallen/plasticity/releases/download/v0.5.32/plasticity_0.5.32_amd64.deb")
>       sha256sums=("530495bbaef5cbdd1346e54801d1dfa770078125074c681c4aee14917332d523")
>       
>       package() {
>         cp -r "$srcdir/usr" -t "$pkgdir"
>       }
>       ```
> 
>     * Run `makepkg` to build the package.
> 
>     * Run `sudo pacman -U plasticity-bin-*.pkg.*` to install.
> 
> 
> To update it:
> 
>     * change `source` to the newer github release URL;
> 
>     * change `pkgver` accordingly;
> 
>     * update the checksum or set it to `SKIP` if you can't be bothered computing it.

I'll base my PKGBUILD package section around yours probably. That's a fine way of doing it. Also as a note, instead of doing `download/v0.5.32/`you should put `download/$v{pkgver}/`. I'll try adding my package to the AUR in a few minutes actually.

**Comment by Techwizz-somboo** [comment]
Guys, it's now in the AUR! It's named `plasticity-bin`.

**Comment by jvanstraten** [comment]
> Also as a note, instead of doing `download/v0.5.32/` you should put `download/$v{pkgver}/`.

Ah yeah, that's nicer indeed. I just wanted something that worked and didn't really bother making it nice. Glad to see you also extended the metadata and didn't just copypaste the bare minimum I bothered to put in it, but I see you listed it as LGPL, which isn't accurate? If any part of a piece of software is nonfree, the package as a whole should also be marked as nonfree. The license of the LGPL part of the software is irrelevant.

**Comment by Techwizz-somboo** [comment]
> > Also as a note, instead of doing `download/v0.5.32/` you should put `download/$v{pkgver}/`.
> 
> Ah yeah, that's nicer indeed. I just wanted something that worked and didn't really bother making it nice. Glad to see you also extended the metadata and didn't just copypaste the bare minimum I bothered to put in it, but I see you listed it as LGPL, which isn't accurate? If any part of a piece of software is nonfree, the package as a whole should also be marked as nonfree. The license of the LGPL part of the software is irrelevant.

Yeah, I see the argument. I agree with you. I'll push an update to the pkgbuild. Thanks!

**Comment by Techwizz-somboo** [comment]
It's updated now. Thanks again for correcting it!

**Comment by nerdCopter** [comment]
just interested in this project (hobbiest).
`yarn install ; yarn start` #same for package, build, etc
bunch of errors and blank UI    :(((`
seems c3d not installed, any directions?
```
ERROR in lib/c3d/enums.ts:1:17
TS2307: Cannot find module '../../build/Release/c3d.node' or its corresponding type declarations.
  > 1 | import c3d from '../../build/Release/c3d.node';
      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```


+1 for AppImage

**Comment by Techwizz-somboo** [comment]
> just interested in this project (hobbiest). `yarn install ; yarn start` #same for package, build, etc bunch of errors and blank UI :(((` seems c3d not installed, any directions?
> 
> ```
> ERROR in lib/c3d/enums.ts:1:17
> TS2307: Cannot find module '../../build/Release/c3d.node' or its corresponding type declarations.
>   > 1 | import c3d from '../../build/Release/c3d.node';
>       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> +1 for AppImage

Read before posting! You can't build it. It requires a closed-source lib that will not be free. https://github.com/nkallen/plasticity/issues/30#issuecomment-1060879159
