### ISSUE TITLE
Extra Dependencies (Linux)

### ISSUE THREAD

**Issue by Techwizz-somboo** [nkallen/plasticity#31]
Hi! The Linux Debian package contains some extra dependencies that are definitely not actually dependencies. For example, Discord is listed as a dependency, but that is definitely not needed. I'd recommend cleaning it up a bit, if you want help knowing what you should remove feel free to ask me and I'll let you know what dependencies shouldn't be listed as required (however you can move them to optional).

**Comment by dumblob** [comment]
Some cleanup will probably be necessary. OTOH discord seems to be the only "support channel" which might be an intention in case of the paid version of Plasticity. IDK
