### ISSUE TITLE
OSX Installation Instructions

### ISSUE THREAD

**Issue by spuder** [nkallen/plasticity#32]
This software looks amazing. 
I'd like to lower the barrier to entry for OSX users by building precompiled packages or add it to homebrew. 

I see a `yarn publish` [step](https://github.com/nkallen/plasticity/blob/master/.github/workflows/ci.yml#L168-L172), but I don't see any OSX or Linux Packages. 

How can this be run on OSX?

**Comment by Fake-User** [comment]
I think there already are precompiled binaries for OSX users, just not in every release. They are labeled as "darwin-x64-#.zip", and the last version was 0.5.13. You can find it here:

https://github.com/nkallen/plasticity/releases/download/v0.5.13/plasticity-darwin-x64-0.5.13.zip

The naming convention gave me a little hiccup at first to. Maybe using obvious words like "OSX" or "Windows" in the titles could make things easier for less technical people.

**Comment by nkallen** [comment]
I feel you... Eventually these are going to be in the App Store and I'll have a web site... Honestly, I did not expect this many users so quickly, I'm a bit overwhelmed
