### ISSUE TITLE
I wonder if Plasticity wouldn't be better off as a paid Blender addon

### ISSUE THREAD

**Issue by darkhog** [nkallen/plasticity#33]
You would not have to develop basic functionality like saving, exporting and the users would have access to the other powerful features of Blender that could either take you years to add to the Plasticity or simply would be out of scope.

**Comment by nkallen** [comment]
Blender is GPL so this is unfortunately impossible

**Comment by darkhog** [comment]
There are several paid blender addons, so it is indeed possible.

W dniu 08.03.2022 o 10:56, Nick Kallen pisze:
