### ISSUE TITLE
Missing contributing guidelines

### ISSUE THREAD

**Issue by andreacavagna01** [nkallen/plasticity#37]
Miss how to install and try the solution, also a Development.md and contributing.md are missing.

I just updated the one for my project. You can take them for example: 
https://github.com/Noovolari/leapp/blob/master/CONTRIBUTING.md
https://github.com/Noovolari/leapp/blob/master/DEVELOPMENT.md

**Comment by nkallen** [comment]
Hi - yes I am thinking about this... I've been a tiny bit hesitant to accept contributions because I haven't fully decided I want to use LGPL and I'm scared of having commits and changing licenses later

**Comment by andreacavagna01** [comment]
You can setup a DCO I think
