### ISSUE TITLE
STL Export

### ISSUE THREAD

**Issue by darkhog** [nkallen/plasticity#40]
I think having it is really needed. Plasticity seems like an easier to use, cheaper alternative to tools like Fusion360 and having an STL export would make it easy to use Plasticity to design 3d prints as all major slicers support STL.

**Comment by PedroRod** [comment]
I second this.

**Comment by Critical11** [comment]
Great suggestion

**Comment by Pontiac76** [comment]
Thirdeded.  I just briefly watched a video on this, and it's MUCH easier to get simple geometry made to do the 3D prints I want to do.  I can appreciate the precision that FreeCad offers, but just making a block with some holes, champers, multi-faced, and multi-blocked is tedious.  I'm not saying it's not worth its weight in gold .. if.. the electrons in an SSD that keep the bit-state the same weighs anything... but for quick things I want to make, this looks to be an awesome tool.  I'll be watching.

**Comment by eGit** [comment]
Doesn't it have obj export? Most slicers should support it. Blender et. al. can import obj and output whatever you want, including STL.

**Comment by dumblob** [comment]
I am also interested in STL export.

**Comment by tolozine** [comment]
I am also want STL export~ very very very wanting ~

**Comment by dumblob** [comment]
@nkallen do you have this in a todo list somewhere? If so, could you please add a tag so that the robot does not close this issue if it gets stale? Thank you!
