### ISSUE TITLE
Please add better navigation for Magic Trackpad

### ISSUE THREAD

**Issue by applebait** [nkallen/plasticity#42]
I'm not getting how to rotate the canvas… I'm using BetterTouchTool which adds the ability to have a Middle Button on the Magic Trackpad but without any success. it could be done, probably, using a modifier key alongside with two fingers.

**Comment by dustinhartlyn** [comment]
I am on a laptop and having a similar problem. Took me a while to figure out to use the center button for rotate. Would be nice if the perspective box in the upper right corner had selectable isometric views (edges of box), or if user could drag over it to rotate the view.

**Comment by nkallen** [comment]
Latest version should have better trackpad support
