### ISSUE TITLE
Rotate with center mouse button cuts off part of the sketch. 

### ISSUE THREAD

**Issue by dustinhartlyn** [nkallen/plasticity#45]
![screen cut off](https://user-images.githubusercontent.com/79132671/158071226-bf5c3803-471c-41ed-b2a3-325f6fdee94e.JPG)

I attached a screen shot of a simple shape that had been rotated with the center button. The bottom half the screen cut off. I could use pan to move everything down.

Running on windows 10

**Comment by UglinessInTheUI** [comment]
Which version of Plasticity are you using ? Different versions seems to have different bugs.
