### ISSUE TITLE
Huge pipe handler

### ISSUE THREAD

**Issue by CGrrrr** [nkallen/plasticity#49]
![pipe](https://user-images.githubusercontent.com/61892991/158495178-8fe2bfff-7c54-4ef2-8259-d2f229c09085.png)

**Comment by nkallen** [comment]
lol that is huge. can you email me and join the discord? I don't have enough time to provide support in two places at the moment.

**Comment by nkallen** [comment]
I fixed it. To be honest, I'm a bit sad, I miss the huge gizmo already
