### ISSUE TITLE
Example files

### ISSUE THREAD

**Issue by andybak** [nkallen/plasticity#50]
I'm the classic "easy distracted, interested in too many things" type of person. I tend to try out new apps several times a week.

It's a _huge_ enticement to play longer when there are a few sample files included so I don't have to figure out what to do with a blank UI.

It's even better if those examples are easily discoverable (in the main menu or in the correct default location when I hit "Open file")

**Comment by nkallen** [comment]
I would recommend you email me for a discord invite. I respond usually in 1-2 days.

I agree with you - without a community of people to help, how would anyone learn new software?

**Comment by andybak** [comment]
Different idea. I definitely advocate example files. Videos are fine but I
personally don't follow tutorials until I'm more invested in a tool.

**Comment by dumblob** [comment]
Ah, I see. Makes sense - complex examples are definitely needed.
