### ISSUE TITLE
Instructional video of modeling a complex example model from zero

### ISSUE THREAD

**Issue by dumblob** [nkallen/plasticity#51]
It's very early but still I believe an instructional video of the whole workflow of modeling a [complex example from zero](https://www.youtube.com/watch?v=aD6pFowpA24 ) (and [second part](https://www.youtube.com/watch?v=5A2r_XZlIco )) would be highly appreciated. It would significantly support the following claim in readme:

>Modelling in Plasticity is quick and efficient due to the unique gizmos, shortcuts, and thoughtful workflow.

**Comment by dumblob** [comment]
Just to clarify - all the videos I've seen so far on Youtube seem still too simplistic. Therefore I've linked the ring example which seems a bit more complicated.

**Comment by nkallen** [comment]
Maybe I'll get to this near launch in September? Producing videos is really hard

**Comment by dumblob** [comment]
>Producing videos is really hard

Yes, I know. Take your time.

Maybe you could ask some of your friends to do the video(s) for you? Maybe even some youngsters would like to increase their "online credit" by helping you out? Or maybe you could partner with some existing youtubers who can at the same time promote this SW?

Maybe I'm overthinking this...

**Comment by nkallen** [comment]
You're not overthinking this. Sorry I'm grumpy because I'm overworked. I mostly interact with people on Discord and I want to slowly add people so I don't have too many bugs to fix at once. So the focus is not "grow as fast as possible" but grow slowly till version 1.0

**Comment by Critical11** [comment]
![image](https://user-images.githubusercontent.com/46278634/158995535-59382178-c888-4629-aa9d-d8595a55a863.png)

**Comment by adrienlemasle** [comment]
Maker Tales released some great tutorials yesterday:
https://www.youtube.com/watch?v=aPtMacvH_10&list=PL6Fiih6ItYsUphPYb1ZTNaaXbKNsT7l39

**Comment by dumblob** [comment]
Oh, sorry for not coming back to this - I actually saw all the tutorials @adrienlemasle linked above and I am amazed.

I am closing this issue as solved by that. Thanks!
