### ISSUE TITLE
BUG: Nothing shown in viewport

### ISSUE THREAD

**Issue by LazeMSS** [nkallen/plasticity#55]
The main view/drawing area is empty and the developer tools shows a lot of GL errors

![image](https://user-images.githubusercontent.com/69049371/159115210-003c7d3d-4f05-48d5-aafe-26bdd739539e.png)

**Comment by UglinessInTheUI** [comment]
I had that problem too a few times. I can't remember if it was caused by the scale tool or something else. Try rotating points on a curve and see if it crashes/breaks/freezes.

**Comment by LazeMSS** [comment]
Hmmm will try. I have tried a lot of things and it might be the old graphic card in my laptop

**Comment by UglinessInTheUI** [comment]
To get back to your case, you probably want to press the / key to get everything centered in the view. When you switch from Perspective to Orthographic the camera flies away from the origin. Use the / key to get back to the center of the grid or select some object and then press / to focus on it. It's like the Numpad Delete key in Blender.

**Comment by LazeMSS** [comment]
Sadly no luck
