### ISSUE TITLE
[Feature request] Scale UI

### ISSUE THREAD

**Issue by matheusfillipe** [nkallen/plasticity#62]
It would be nice to scale the user interface scaling. It looks small to me.

**Comment by nkallen** [comment]
You could try <ctrl> <shift> <+> (plus) , it might work. but it might screw everything up too

**Comment by matheusfillipe** [comment]
Just '+' ? Doesn't do anything to me. Neither '-' or the numpad ones or with ctrl or shift. I am on 0.5.39, maybe thats on the newer versions?

**Comment by nkallen** [comment]
ctrl shift plus should work (?)

**Comment by matheusfillipe** [comment]
Nope. I tried every combination with ctrl shift and alt + "-" key and "=" and numpad "-" and "+". 

I am on arch linux.

**Comment by eGit** [comment]
You could check the DPI settings of your OS or search for scaling withing the "Electron App", on which Plasticity is based.
