### ISSUE TITLE
Be Open-Source

### ISSUE THREAD

**Issue by secretgspot** [nkallen/plasticity#63]
This has the feel and direction of Fusion360, however you stated that you wanted to go commercial which will make you a direct competitor for Fusion360 and that's a bad thing.  Instead I beg of you to take it Blender route and develop it into full on Fusion360 open-source competitor so it can grow and overshadow as Blender did with Maya.

**Comment by eGit** [comment]
The main problem is probably the C3D kernel. If you know of an Open Source replacement, Nick would be more then happy to use it.

**Comment by nkallen** [comment]
Direct modeling is the key feature in Plasticity (and Fusion) and there is no open source geometry kernel with a mature direct modeling implementation. Fusion is awesome but it is focused on manufacturing, and I feel/hope the workflow of Plasticity will be distinct enough that no one will really see it as a Fusion competitor. Hard surface artists who currently use and love fusion may hesitate, but my impression from talking to many hard surface artists who use Fusion is that it is "powerful" and "usable" but they are largely dissatisfied with the workflow and price.

**Comment by hurricanz** [comment]
> This has the feel and direction of Fusion360, however you stated that you wanted to go commercial which will make you a direct competitor for Fusion360 and that's a bad thing. Instead I beg of you to take it Blender route and develop it into full on Fusion360 open-source competitor so it can grow and overshadow as Blender did with Maya.

Blender didn't overtake Maya.   There are still more jobs for Maya compared to blender.  It's just a fact.   I support buying this software.  He shouldn't be making this app for free just because YOU feel you it should be.   Blender kiddies can be so self-righteous and demanding. They are the Vegan Karens of the 3D community.
