### ISSUE TITLE
keymap.json bug? plasticity 0.5.47 windows 10

### ISSUE THREAD

**Issue by piokud84** [nkallen/plasticity#68]
I edited ...\AppData\Local\plasticity\app-0.5.47\resources\app\.webpack\main\dot-plasticity\keymap.json

....
```
    "orbit-controls": {
        // Uncomment to get maya-style orbit/pan.
        // "alt-mouse0": "orbit:rotate",
        // "alt-mouse1": "orbit:pan",
        // "alt-mouse2": "orbit:dolly"

        // Uncomment to get blender-style orbit/pan.
        // "mouse1": "orbit:rotate",
        // "shift-mouse1": "orbit:pan",
    }
}
```

to
...
```
    "orbit-controls": {
        // Uncomment to get maya-style orbit/pan.
        // "alt-mouse0": "orbit:rotate",
        // "alt-mouse1": "orbit:pan",
        // "alt-mouse2": "orbit:dolly"

        // Uncomment to get blender-style orbit/pan.
        "mouse2": "orbit:rotate",
        "mouse1": "orbit:pan",
    }
}

```
edit did not change any of Keybindings behavior

so i changed ...\AppData\Local\plasticity\app-0.5.47\resources\app\.webpack\main\index.js

... `{case"default":u["orbit-controls"]={mouse1:"orbit:rotate",mouse2:"orbit:pan"};` ...

to
... `{case"default":u["orbit-controls"]={mouse2:"orbit:rotate",mouse1:"orbit:pan"};` ...

and it worked.

Why edited \AppData\Local\plasticity\app-0.5.47\resources\app\.webpack\main\dot-plasticity\keymap.json does not affect any Keybindings behavior, am i missing something or is it a bug ?

**Comment by nkallen** [comment]
It's not in AppData, it's in c:\users\piokud84\\.plasticity\keymap.json

**Comment by nkallen** [comment]
However if you're just changing the orbit stuff, check the "Keybindings" menu in the app, it allows you to quickly switch to blender style orbiting

**Comment by piokud84** [comment]
`However if you're just changing the orbit stuff, check the "Keybindings" menu in the app, it allows you to quickly switch to blender style orbiting`

Menu was the 1st thing i tryed ;), none of keybindings had preset i was looking for (rmb = rotate, mmb = pan, both with no keyboard key modifier - oposite of default settings).
