### ISSUE TITLE
v0.5.60 does not contain mac artifacts

### ISSUE THREAD

**Issue by leon** [nkallen/plasticity#73]
The v0.5.59 release contains the darwin build artifacts but not the new stable release.
are the artifacts generated or manually uploaded?

Ps.
Loving the app 😄

**Comment by rsaccon** [comment]
The latest mac release is always one release behind. I don't know why but it has been mentioned and explained here before.

**Comment by nkallen** [comment]
yeah... just an artifact of the current build process. Mac 0.5.59 is actually windows 0.5.60
