### ISSUE TITLE
Feature Request:  Add fast view changes similar to blender by holding Alt middle mouse button and dragging along the direction you want to view

### ISSUE THREAD

**Issue by mremmert23** [nkallen/plasticity#74]

**Comment by nkallen** [comment]
I will do this summertime

Blender has two approaches to this --

1. if you hold alt and THEN middle drag it snaps only to top/right/bottom/left
2. If you middle drag and then tap and hold alt it snaps to t/r/b/l and various 3/4 views

I'm going to do just one of the two. I think more people use #1 but I tend to prefer #2, it's less jarring
