### ISSUE TITLE
Image Planes are not saved with file.

### ISSUE THREAD

**Issue by therendermonkey** [nkallen/plasticity#76]
Image plane empties are not saved in the file. When the c3d file is reopened there are no images and no Empties

(Tested plasticity_0.6.9_amd64.deb on Linux Mint 20.3 Cinnamon and plasticity-darwin-x64-0.6.9.zip on Big Sur 11.6.1 Intel)

Also, on Linux the file extension is not automatically filled into the save as dialog, if it is not entered manually the document will appear to save, but is not actually saved. Extension seems to be created automatically on OSX.)

**Comment by nkallen** [comment]
In more recent versions you can save the .plasticity format which includes references and groups
