### ISSUE TITLE
Darwin arm64 0.6.19 release appears to be damaged and won't run 

### ISSUE THREAD

**Issue by johnaquilina** [nkallen/plasticity#80]
Darwin arm64 0.6.19 release appears to be damaged and won't run.

I have attached the message I get when I try to run the application and the About This Mac Dialog.

<img width="262" alt="Screenshot 2022-05-28 at 08 38 37" src="https://user-images.githubusercontent.com/65115012/170815887-ef8ce81d-5413-486e-823c-12d4eaadffc5.png">
<img width="589" alt="Screenshot 2022-05-28 at 08 43 05" src="https://user-images.githubusercontent.com/65115012/170815962-e9043603-4bf2-4786-ac30-e1795588df02.png">

**Comment by NoobTaco** [comment]
I just ran into the same issue. 

Tried downloading with both chrome and safari
<img width="698" alt="Screen Shot 2022-05-28 at 8 31 20 AM" src="https://user-images.githubusercontent.com/1172935/170832077-8e85cc3f-9df7-408a-b09c-fc6c37d5afb6.png">

**Comment by johnaquilina** [comment]
Thanks for replying, so the message is generated because the executable is not signed?

Regards,

John

**Comment by nkallen** [comment]
yes it's not signed

**Comment by johnaquilina** [comment]
Thanks for telling me, as you suggested earlier I can use xattr to remove it from quarantine and use it. You can close the ticket now.

**Comment by Harry-Harrison** [comment]
If anyone else lands on this and has no idea what it means. CD to the directory of the app you've unzipped and run this in your Terminal app `xattr -cr plasticity.app`

It won't return a success message, but now when you try to open it, it'll just open.
