### ISSUE TITLE
Support for 3DConnexion SpaceMouse

### ISSUE THREAD

**Issue by Zima3D** [nkallen/plasticity#83]
Hi. I started using Plasticity few days ago and it is awesome software. As I usualy use my Space Mouse with 3D software I really miss it in Plasticity.

Would there be a chance to add this somehow please?

**Comment by nkallen** [comment]
I will add it but not for several months

**Comment by phranck** [comment]
Any news about this topic? I just heard about Plasticity two days ago. Will it support the 3DConnexion SpaceMouse?

**Comment by gilarto** [comment]
Same here! please implement support for the space mouse, it would be a deal breaker for me (to actually buy the indie license)

**Comment by j2cncdesign** [comment]
> I will add it but not for several months

Hi, is this implemented now?  I just bought Plasticity and am planning on getting a spacemouse asap.
